org: tochukz
service: serverless-bookapi
frameworkVersion: '3'

provider:
  name: aws 
  deploymentMethod: direct 
  deploymentBucket: 
    name: bookapi-deploys-artifacts
    versioning: false
  stage: staging
  region: eu-west-2
  runtime: nodejs14.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
      
plugins:
  - serverless-offline